recipes:
  - ./roles/base.rb
git:
  version: 2.14.5
ruby:
  version: 2.6.0
  user: ec2-user
  path: /usr/local/.rbenv
redmine:
  path: /var/lib/redmine
# redmineが2系サポートしてない...
bundler:
  version: 1.17.2
